#!/bin/bash
userdel -rf k1am
userdel -rf k1bm
userdel -rf k1cm
userdel -rf k2am
userdel -rf k2bm
userdel -rf k2cm
userdel -rf k3am
userdel -rf k3bm
userdel -rf k3cm
userdel -rf k4am
userdel -rf k4bm
userdel -rf k4cm
userdel -rf k5am
userdel -rf k5bm
userdel -rf k5cm
userdel -rf k1af
userdel -rf k1bf
userdel -rf k2af
userdel -rf k2bf
userdel -rf k3afi
userdel -rf k3bfn
userdel -rf k4afi
userdel -rf k4bfn
userdel -rf k1ai
userdel -rf k1bi
userdel -rf k1ci
userdel -rf k2ai
userdel -rf k2bi
userdel -rf k2ci
userdel -rf k3ai
userdel -rf k3bi
userdel -rf k3ci
userdel -rf k4ax
userdel -rf k4bi
userdel -rf k4cn
userdel -rf k5ai
userdel -rf k5bn
userdel -rf k5cn
userdel -rf k1ao
